generateQuote(); 
document.getElementById('generateBtn').addEventListener('click', generateQuote);
function generateQuote() {
    let quotes =  {
            '― Albert Einstein': '“Our task must be to free ourselves... by widening our circle of compassion to embrace all living creatures and the whole of nature and its beauty.”',
            '― Pierce Brown': '“Man cannot be freed by the same injustice that enslaved it.”',
            '― Madeline Miller': '“Bury us, and mark our names above. Let us be free.”',
            '― Aaron Lauritsen': '“There is strange comfort in knowing that no matter what happens today, the Sun will rise again tomorrow.”',
            '― C.S. Lewis': '“I was not born to be free---I was born to adore and obey.”',
            '― Maya Angelou': '“You may not control all the events that happen to you, but you can decide not to be reduced by them.”',
            '― Dr. Seuss': '“Today you are you, that is truer than true. There is no one alive who is youer than you.”',
            '― Mark Twain': '“The two most important days in your life are the day you are born and the day you find out why.”',
            '― Oprah Winfrey': '“Turn your wounds into wisdom.”',
            '― Albert Camus': '“In the midst of winter, I found there was, within me, an invincible summer.”',
            '― J.K. Rowling': '“It does not do to dwell on dreams and forget to live.”',
            '― John F. Kennedy': '“Change is the law of life. And those who look only to the past or present are certain to miss the future.”',
            '― Helen Keller': '“The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.”',
            '― Winston S. Churchill': '“Success is not final, failure is not fatal: It is the courage to continue that counts.”',
            '― Mahatma Gandhi': '“The best way to find yourself is to lose yourself in the service of others.”',
            '― Leo Tolstoy': '“All, everything that I understand, I understand only because I love.”',
            '― Nelson Mandela': '“I learned that courage was not the absence of fear, but the triumph over it.”',
            '― Stephen Hawking': '“Remember to look up at the stars and not down at your feet.”',
            '― Frida Kahlo': '“I am my own muse. I am the subject I know best. The subject I want to know better.”',
            '― Martin Luther King Jr.': '“Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.”',
            '― Jane Austen': '“I declare after all there is no enjoyment like reading! How much sooner one tires of anything than of a book!”',
            '― Ralph Waldo Emerson': '“To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.”',
            '― J.R.R. Tolkien': '“Not all those who wander are lost.”',
            '― Emily Dickinson': '“Hope is the thing with feathers that perches in the soul, and sings the tune without the words, and never stops at all.”',
            '― Charles Dickens': '“It was the best of times, it was the worst of times.”',
            '― Virginia Woolf': '“Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.”',
            '― Albert Schweitzer': '“The purpose of human life is to serve and to show compassion and the will to help others.”',
            '― William Shakespeare': '“All the world\'s a stage, and all the men and women merely players.”',
            '― Mother Teresa': '“Spread love everywhere you go. Let no one ever come to you without leaving happier.”',
            '― Albert Camus': '“In the depths of winter, I finally learned that within me there lay an invincible summer.”',
            '― Maya Angelou': '“We may encounter many defeats but we must not be defeated.”',
            '― Martin Luther King Jr.': '“The time is always right to do what is right.”',
            '― Neil Armstrong': '“That\'s one small step for a man, a giant leap for mankind.”',
            '― Stephen Hawking': '“The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.”',
            '― Mahatma Gandhi': '“Live as if you were to die tomorrow. Learn as if you were to live forever.”',
            '― Nelson Mandela': '“Education is the most powerful weapon which you can use to change the world.”',
            '― Jane Austen': '“There is no charm equal to tenderness of heart.”',
            '― William Shakespeare': '“The better part of Valour, is Discretion: in the which better part, I haue saued my life.”',
            '― C.S. Lewis': '“To love at all is to be vulnerable. Love anything and your heart will be wrung and possibly broken.”',
            '― Dr. Seuss': '“Unless someone like you cares a whole awful lot, nothing is going to get better. It’s not.”',
            '― Emily Dickinson': '“I’m nobody! Who are you? Are you nobody, too?”',
            '― Albert Einstein': '“Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world.”',
            '― Stephen King': '“Books are a uniquely portable magic.”',
            '― Oscar Wilde': '“To live is the rarest thing in the world. Most people exist, that is all.”',
            '― J.R.R. Tolkien': '“Even the darkest night will end and the sun will rise.”',
            '― Virginia Woolf': '“I am rooted, but I flow.”',
            '― Albert Schweitzer': '“The only ones among you who will be really happy are those who will have sought and found how to serve.”',
            '― Charles Dickens': '“I have been bent and broken, but – I hope – into a better shape.”',
            '― Mother Teresa': '“If you judge people, you have no time to love them.”',
        }   
    let authors = Object.keys(quotes);
    let author = authors[Math.floor(Math.random() * authors.length)];
    let quote = quotes[author];
    document.getElementById('quote').innerHTML = quote;
    document.getElementById('author').innerHTML = author;
};